#!/bin/sh

# Nagios plugin to check if there are livepatches pending.
# Copyright (C) 2017 Simon Deziel <simon@sdeziel.info>

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# Explicitly set the PATH to that of ENV_SUPATH in /etc/login.defs and unset
# various other variables. For details, see:
# https://wiki.ubuntu.com/SecurityTeam/AppArmorPolicyReview#Execute_rules
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
export ENV=
export CDPATH=
export LC_ALL="C"

if ! which canonical-livepatch > /dev/null 2>&1; then
  echo "LIVEPATCH UNKNOWN: No canonical-livepatch binary"
  exit 3
fi

OUTPUT="$(canonical-livepatch status --verbose)"
cve_count="$(echo "$OUTPUT" | grep -cF "CVE-")"

if echo "$OUTPUT" | grep -q "patchState: nothing-to-apply$"; then
  echo "LIVEPATCH OK: nothing to apply ($cve_count already applied)"
  exit 0
fi

echo "LIVEPATCH CRITICAL: live patches pending"
exit 1
